### ISSUE TITLE
out of the array bound in SRC/slaset.f

### ISSUE THREAD

**Issue by collinmines** [Reference-LAPACK/lapack#318]
The previous issues with some array access in LAPACK 3.8.0 have been fixed, so please cf.  #312. 

Here I'm reporting the other out of array bound issue in ./EIG/xeigtsts. What I did is same as before: LAPACK 3.8.0, GCC (gfortran v8.2.1), appended "-fcheck=all" in "OPTS" of make.inc, then run "make all".

Below is the detail:
...
./EIG/xeigtsts < se2.in > sse2.out 2>&1
make[1]: *** [sse2.out] Error 2
make[1]: Leaving directory `../lapack/TESTING'
make: *** [lapack_testing] Error 2

The content of **sse2.out** is:

At line 169 of file **slaset.f**
Fortran runtime error: Index '2' of dimension 1 of array 'a' above upper bound of 1

Error termination. Backtrace:
#0 0x10000042ddaf in ???
#1 0x10000042f7e7 in ???
#2 0x10000043019b in ???
#3 0x101c9107 in ???
#4 0x1002889b in ???
#5 0x10005a13 in ???
#6 0x10001313 in ???
#7 0x100000764bf7 in ???
#8 0x100000764e03 in ???
#9 0xffffffffffffffff in ???
Tests of the Symmetric Eigenvalue Problem routines

LAPACK VERSION 3.8.0

The following parameter values will be used:
M: 0 1 2 3 5 20
N: 0 1 2 3 5 20
NB: 1 3 3 3 10
NBMIN: 2 2 2 2 2
NX: 1 0 5 9 1

Relative machine underflow is taken to be 0.117549E-37
Relative machine overflow is taken to be 0.340282E+39
Relative machine precision is taken to be 0.596046E-07

Routines pass computational tests if test ratio is less than 50.00
SST routines passed the tests of the error exits (209 tests done)
SE2: NB = 1, NBMIN = 2, NX = 1

Thanks a lot for your time again!
Collin

**Comment by collinmines** [comment]
Thanks, @langou . Please let me know when the bugs have been fixed so I'll test it again.
Collin
